class locators {

  constructor() {

    this.Account_FirstValue = '(//tbody//following::tr[1]/td[2])[1]';
    this.Account_value = '//div[text()="Open"]//following::div[1]';
    this.Account_value_Close = '//div[text()="Open"]//following::button[2]';
    this.Open_NewTab = '(//tbody//tr[3]/td[2]//*[local-name()="svg"])[2]';
    this.account_dropdown = '#fa-at-link--accounts';
    this.Page_title1 = '#fa-at-text--page-title';
    this.workflows_Title = '//*[text()="Workflows"]';
    this.WorkFlows = '//h6[text()="Workflows"]';
    this.attribution_Pagetitle = '//*[text()="Attribution Reports"]';
    this.account_identification_Title = '//h4[text()="Top accounts that visited your website"]';
    this.report_dropdown = '#fa-at-link--journeys';
    this.attributes = '//*[text()="Attribution"]';
    this.usermail = '#fa-at-dropdown--projects div.opacity-80';
    this.setting = '#fa-at-dropdown--settings';
    this.Account_identification = '//*[text()="Account identification"]';
    this.identi_table = '.ant-table-container';
    this.Identification_Table = '.data-table';
    this.table_row1 = '//tbody/tr[1]';
    this.table_row2 = '//tbody/tr[2]';
    this.channel = '.gap-4 > :nth-child(1) > .ant-btn';
    this.channel_dropdown = '.fa-select-dropdown > .flex';
    this.Organic_Search = '[data-title="Organic Search"]';
    this.organic_table1 = '//tbody/tr[1]/td[2]';
    this.organic_table2 = '//tbody/tr[2]/td[2]';
    this.organic_table3 = '//tbody/tr[3]/td[2]';
    this.direct = '[data-title="Direct"]';
    this.paid_search = '[data-title="Paid Search"]';
    this.campaign = '.gap-4 > :nth-child(2) > div > .ant-btn';
    this.campaign_dropdown = '.fa-select-dropdown';
    this.TD_Search_Remarketing_Competitors = '[data-title="TD_Search_Remarketing_Competitors"]';
    this.Apply = '.fa-select--buttons > .ant-btn';
    this.TD_Search_US_Deanon_Competition = '[data-title="TD_Search_US_Deanon_Competition"]';
    this.page_view = '.gap-4 > :nth-child(3) > div > .ant-btn';
    this.pageview_option1 = '//input[@placeholder="Search"]//following::div[@data-title][1]';
    this.pageview_option2 = '//input[@placeholder="Search"]//following::div[@data-title][2]';
    this.pageview_option3 = '//input[@placeholder="Search"]//following::div[@data-title][3]';
    this.pageview_option4 = '//input[@placeholder="Search"]//following::div[@data-title][4]';
    this.Upgrade_validation = '.ant-modal-body';
    this.Filter_option2 = '//input[@placeholder="Select Property"]//following::div[@data-title][2]';
    this.Filter_option1 = '//input[@placeholder="Select Property"]//following::div[@data-title][1]';
    this.identi_table1 = '.ant-table-wrapper';
    this.calender = '//button[contains(@class,"customButton")]/span';
    this.Last_7_Days = '[data-title="Last 7 Days"]';
    this.select_date = '//div[@data-title="Today"]//following::div[3]';
    this.ShareBtn = '//span[text()="Share"]/ancestor::button';
    this.share1 = '//span[text()="Share"]'
    this.email_field = '#share-modal-form_emails_0';
    this.done = '[type="submit"]';
    this.Continue = '//*[text()="Continue"]';
    this.notification_popup = '.ant-notification-notice';
    this.notification_popup1 = '.ant-notification-notice-message';
    this.notification_popup3 = '.ant-notification';
    this.clear = '//span[text()="Clear all"]';
    this.search = '//div[text()="Top accounts"]//following::button[1]';
    this.Klenty_details = '//tbody/tr[1]/td[1]';
    this.X_button = '//input[@placeholder="Search"]//following::button[1]';
    this.download = '//div[text()="Top accounts"]//following::button[2]';
    this.account_pageloaded = '//tbody';
    this.factors_File = '//tbody/tr[2]/td[2]';
    this.search_button = '(//*[local-name()="svg" and @data-icon="magnifying-glass"])[2]';
    this.search_button1 = '//*[local-name()="svg" and @data-icon="magnifying-glass"]';
    this.search_area = '//*[@placeholder="Search Account"]';
    this.People_download_button = '//span[text()="Filter"]//following::button[6]';
    this.download_header = '//input[@placeholder="Search properties"]//preceding::h5[1]';
    this.exportCSV = '//span[text()="Export CSV"]';
    this.filter = '.w-full > .ant-btn';
    this.view_filter = '.justify-center > span';
    this.filter_css = '.w-full > .ant-btn-text';
    this.Add_filter = '(//*[text()="Add filter"])[1]';
    this.Visited_Website = '[data-title="Visited Website"]';
    this.Visited_Website1 = '[title="Visited Website"]';
    this.true = '[data-title="True"]';
    this.true1 = '[data-title="true"]';
    this.Add_event = '//*[text()="Add event"]';
    this.select_option = '//input[@placeholder="Select Event"]//following::div[3]';
    this.filter_closebtn = '//*[@placeholder="Search Users"]//following::button[1]';
    this.segment_name = '//input[@type="text" and @placeholder="Name"]';
    this.segment_rename = '[placeholder="Name"]';
    this.Save = '//*[text()="Save"]';
    this.Search_segment = '[placeholder="Search segment"]';
    this.Saved_segment = '//input[@placeholder="Search segment"]//following::div[2]';
    this.Select_segment = '//span[text()="New Segment"]//preceding::div[6]';
    this.Delete_segment1 = '(//div[text()="Delete segment"])[1]';
    this.confirm = '//*[text()="Confirm"]';
    this.Table_properties = '.ant-popover-inner-content';
    this.Apply1 = '//span[text()="Apply"]';
    this.People = '//*[text()="People"]';
    this.Search1 = '//*[@placeholder="Search Users"]';
    this.rowname = '//tbody/tr[2]/td[1]';
    this.table_property = '.ant-tabs';
    this.company_name1 = '//*[text()="Company Country"]';
    this.CompanyCountryISOCode = '(//*[text()="Company Country ISO Code"])[1]';
    this.Add_filter1 = '//*[text()="Add filter"]';
    this.others = '[data-title="OTHERS"]';
    this.others1 = '[data-title="Others"]';
    this.login_option = '[data-title="LOGIN"]';
    this.Run_Query = '[data-title="RUN-QUERY"]';
    this.segment_namefield = '//*[@placeholder="Eg- Paid search visitors"]';
    this.seg_rename = '//*[@placeholder="Name"]';
    this.save1 = '(//span[text()="Save"])[2]';
    this.save2 = '(//span[text()="Save"])[1]';
    this.Automation = '//*[text()="Automations"]';
    this.create_new = '(//div[text()="Create New"])[1]';
    this.Account_click = '.active';
    this.alert_page = '.ant-form';
    this.select_event = '//*[text()="Event details"]//following::span[text()="Select Event"]';
    this.select_event_1 = '//span[text()="Select Event"]';
    this.search_1 = '[placeholder="Search"]';
    this.Alert_name = '#alert_name';
    this.Add_property = '.ant-col > .ant-btn';
    this.Company_option = '(//div[@data-title="Company Name"])[1]';
    this.Enable_button = '(//button[@role="switch"])[1]';
    this.remove_alert = '//div[text()="Delete alert"]';
    this.Ok = '//span[text()="OK"]';
    this.Ok1 = '//span[text()="Ok"]';
    this.select_property = '[placeholder="Select Property"]';
    this.Add_First_Event = '//span[text()="Add First Event"]';
    this.Website_Session = '[data-title="Website Session"]';
    this.Website_Session1 = '[title="Website Session"]';
    this.add_new_3 = '(//*[text()="Add new"])[1]';
    this.All_Account = '[data-title="All Accounts"]';
    this.false = '//span[text()="Clear all"]//following::div[1]';
    this.choose_date = '[data-menu-id]';
    this.Add_a_KPI = '//span[text()="Add a KPI"]';
    this.Total_Session = '[data-title="Total Sessions"]';
    this.Channel_option = '[data-title="Channel"]';
    this.table_validation1 = 'tbody.ant-table-tbody > tr:nth-child(2) > td:nth-child(1)';
    this.table_validation2 = 'tbody.ant-table-tbody > tr:nth-child(3) > td:nth-child(1)';
    this.open_account = '(//a[text()="infosys.com"])//following::button[1]';
    this.BirdView = '//span[text()="Birdview"]';
    this.View_visible = '//div[contains(@id,"panel-birdview")]//child::tbody/tr[1]';
    this.Expand = '//span[text()="Birdview"]//following::button[2]';
    this.collapse = '//span[text()="Birdview"]//following::button[3]';
    this.First_value = '//*[text()="Date and Time"]//following::div[@class="tag"][1]';
    this.Birdview_option = '//span[text()="Birdview"]//following::button[4]';
    this.Company_Created = '//*[text()="Company Created"]';
    this.Event_validation = ':nth-child(1) > .bg-gradient--44px.pb-NaN > .timeline-events';
    this.Birdview_properties = '//div[contains(@id,"tab-properties")]';
    this.property_validation = '//*[text()="Date and Time"]//following::h4[2]';
    this.Birdview_properties_option1 = '//input[@placeholder="Select a User Property"]//following::div[11]';
    this.Add_Property1 = '//span[text()="Add property"]';
    this.Company_Identification = '[data-title="Company Identification"]';
    this.Company_Identification1 = '[title="Company Identification"]';
    this.Company_domain = '[data-title="Company Domain"]';
    this.TopEngagementSignal = '[title="Top Engagement Signals"]'
    this.time_dropdown = '//span[text()="Birdview"]//following::button[5]';
    this.timestamp_validation = ':nth-child(1) > :nth-child(1) > .timestamp';
    this.Time_stamp = '//*[text()="Timestamp"]';
    this.Hourly = '//*[text()="Hourly"]';
    this.Weekly = '//*[text()="Weekly"]';
    this.Monthly = '//*[text()="Monthly"]';
    this.Daily = '//*[text()="Daily"]';
    this.Time_line = '//*[text()="Timeline"]';
    this.Time_line_Validation = '//div[contains(@id,"panel-timeline")]';
    this.Over_view = '//*[text()="Overview"]';
    this.Over_view_validation = '.overview';
    this.people_firstvalue = '//th[text()="Date and Time"]//following::span[1]';
    this.Milestones_peopleView = '//span[text()="Milestones"]';
    this.Milestones_option = '//div[contains(@id,"panel-milestones")]//h4';
    this.notification_popup2 = '.ant-notification-notice-with-icon';
    this.Apply2 = '//*[text()="Apply"]';
    this.email = '[data-title="email"]';
    this.email_1 = '[data-title="is_email_verified"]';
    this.User_identification = '[data-title="User Identification"]';
    this.Send_Once = '#share-modal-form_subscriptionType > :nth-child(1)';
    this.copy_Link = '//span[text()="Copy link"]';
    this.Clear_All_Filter = '//h1[text()="Clear all filters"]';
    this.Discard_Filter = '//span[text()="Discard changes"]';
    this.clear_search = '//form[@id="basic"]//following::button[1]';
    this.New_Segment = '//span[text()="New Segment"]';
    this.save_field = '//div[@class="flex flex-col gap-y-2"]//input[@placeholder="Eg- Paid search visitors"]';
    this.In_Hubspot1 = '[data-title="In Hubspot"]';
    this.In_Hubspot2 = '[title="In Hubspot"]';
    this.Add_Report = '//span[text()=" Add Report"]';
    this.Add_Report_1 = '//Div[text()="Add Report"]';
    this.Add_KPI1 = '//span[text()="Add KPI"]';
    this.Filter_this_Attribute = '//*[text()="CONVERSION GOALS"]//following::button[2]';
    this.Filter_By = '//*[text()="Filter By"]';
    this.Tactic = '[value="Tactic"]';
    this.Offer = '[value="Offer"]';
    this.Tactic_Offer = '[value="TacticOffer"]';
    this.Add_a_Property = '//span[text()="Add a Property"]';
    this.Campaign1 = '[title="Campaign"]';
    this.Add_Model = '//span[text()="Add Model"]';
    this.First_Touch = '[title="First Touch"]';
    this.Add_Compare_Model = '//*[text()="Attribution Model"]//following::button[2]';
    this.Last_Touch = '[title="Last Touch"]';
    this.Last_7_days = '//a[text()="Last 7 days"]';
    this.Run_Analysis1 = '//span[text()="Run Analysis"]';
    this.Attri_pageloaded = '.mt-12';
    this.Dashboards = '//*[text()="Dashboards"]';
    this.Event_Report = '//*[text()="New Event Report"]';
    this.Sparkline = '//span[text()="Sparkline"]';
    this.Line_Chart = '//*[text()="Line Chart"]';
    this.Filter_this_event = '//*[text()="EVENTS"]//following::button[3]';
    this.session_properties = '[data-title="Session Properties"]';
    this.breakdown_option = '//*[text()="EVENTS"]//following::button[2]';
    this.BreakDown = '//span[text()="Breakdown"]';
    this.Traffic_source = '[data-title="Traffic Source"]';
    this.Content_Groups = '//span[text()="Content Groups"]';
    this.Add_New = '//span[text()="Add New"]';
    this.Add_new2 = '//span[text()="Add new"]';
    this.content_group_name = '#content_group_name';
    this.content_group_description = '#content_group_description';
    this.New_Value = '//span[text()="New value"]';
    this.New_value_1 = '//span[text()="New Value"]';
    this.content_group_value = '#content_group_value';
    this.Add_Rule = '//span[text()="Add rule"]';
    this.page_value = '#rule_0_va';
    this.Or_value = '[value="OR"]';
    this.Contains = '[title="Contains"]';
    this.Equals = '[title="Equals"]';
    this.equals_1 = '[data-title="equals"]';
    this.Remove = '//a[text()="Remove"]';
    this.confirm_1 = '//span[text()="Confirm"]';
    this.Name = '#name';
    this.description = '#description';
    this.Default = '[title="Default"]';
    this.Derived_KPI = '[title="Derived KPI"]';
    this.Select_Event = '[placeholder="Select Event"]';
    this.Add_another_KPI = '//span[text()="Add another KPI"]';
    this.KPI_option_1 = '//input[@placeholder="Select Event"]//following::div[4]';
    this.Formula = '#for';
    this.showAspercentage = '#showAspercentage';
    this.Remove_1 = '//span[text()="Remove"]';
    this.Engagement_Category = '//span[text()="Engagement Category"]';
    this.Hot_Input = '//span[text()="Hot"]//following::input[1]';
    this.Warm_Input = '//span[text()="Warm"]//following::input[1]';
    this.Cool_Input = '//span[text()="Cool"]//following::input[1]';
    this.Apply_Changes1 = '//span[text()="Apply Changes"]';
    this.Reset_to_Default = '//span[text()="Reset to Default"]';
    this.Add_signal = '//span[text()="Add signal"]';
    this.Pricing_page_visit_Search = '//textarea[text()="Untitled"]';
    this.Assign_weight = '//span[text()="70"]';
    this.Assign_weight1 = '//span[text()="60"]';
    this.Yes = '//span[text()="Yes"]';
    this.Pricing = '//h4[text()="Plans & Billings"]';
    this.Integrations = '//span[text()="Integrations"]';
    this.Enrichment_Source = '[data-title="Enrichment Source"]';
    this.Enrichment_Source1 = '[title="Enrichment Source"]';
    this.Acc_Iden_enrich = '//*[text()="Factors Account Identification"]';
    this.upgrade_plan = '.mt-5 > .ant-btn';
    this.upgrade_title = '.fai-text__size--h4';
    this.Buy_this_Plan = '(//span[text()="Buy this Plan"])[1]';
    this.Enrichment_Rules = '//div[text()="Enrichment Rules"]';
    this.Set_custom_rules = '//input[@type="radio" and @value="true"]';
    this.Select_Pages = '//span[text()="Select pages"]';
    this.Upload_List = '//span[text()="Upload List"]';
    this.CSVUploadModal_popup = '//div[@role="dialog" and contains(@class,"CSVUploadModal")]';
    this.File = '//a[text()="file"]';
    this.File_Upload = 'input[type="file"]';
    this.UploadandContinue = '//span[text()="Upload and Continue"]';
    this.Enrichment_page_validation = '//span[text()="Include"]//following::div[contains(@class,"SixSignalFactors__customSelect")]';
    this.Enrichment_Uploaded_Verify = '//*[text()="Include"]//following::div[1]';
    this.Save_Changes = '//span[text()="Save Changes "]';
    this.Save_Changes_New = '//span[text()="Save Changes"]';
    this.Savechanges1 = '//span[text()="Save changes"]';
    this.close_new = '//*[text()="Include"]//preceding::button[1]';
    this.Delete = '//a[text()="Delete Report"]';
    this.New_Event = '//span[text()="New Event"]';
    this.Source = '#source';
    this.Hubspot = '[data-title="Hubspot"]';
    this.Hubspot1 = '[title="Hubspot"]';
    this.Object_type = '#object_type';
    this.Deal = '[title="deal"]';
    this.Property_name = '#property_name';
    this.Record_modified_time = '//span[text()="Record modified time"]';
    this.Save_1 = '//span[text()="Save"]';
    this.Popup_Message = '.ant-message-notice-content';
    this.View_Event = '//a[text()="View Event"]';
    this.Remove_Event = '//a[text()="Remove Event"]';
    this.New_Report_CSS = '#fa-at-btn--new-report';
    this.Funnel_Report = '//*[text()="New Funnel Report"]';
    this.Add_another_event = '//span[text()="Add another event"]';
    this.Linkedin_Company_Engagements = '[data-title="Linkedin Company Engagements"]';
    this.Filter_By_CSS = '.query_card_open-add > :nth-child(1) > :nth-child(4)';
    this.Filter_this_funnel = '//*[text()="Analyse"]//following::button[3]';
    this.Delete_this_funnel = '//*[text()="Analyse"]//following::button[8]';
    this.Add_New_FilterBy = '(//*[text()="FILTER BY"])//following::span[text()="Add new"][1]';
    this.Add_New_FilterBy1 = '//*[text()="FILTER BY"]//following::span[text()="Add new"][1]';
    this.Plus_Button = '//*[text()="FILTER BY"]//following::button[@index="0"]';
    this.Or = '//*[text()="FILTER BY"]//following::h6[2]';
    this.or_1 = '//*[text()="PROFILES TO ANALYSE"]//following::h6[3]';
    this.Add_New_Breakdown = '(//div[@class="flex relative"]//button)';
    this.Add_New_Breakdown_new = '.m-0 > .flex > .ant-btn > span';
    this.Conversion_Window = '//*[text()="Conversion within"]//following::div[1]';
    this.Tooltip = '[role="tooltip"]';
    this.Date_select = '(//div[@role="tooltip"]//following::span)[2]';
    this.Hours = '[title="Hours"]';
    this.Minutes = '[title="Minutes"]';
    this.Days = '[title="Days"]';
    this.calender_MenuList = '(//*[text()="FUNNEL CRITERIA"])//following::button[1]';
    this.Menu_Item = '[role="menuitem"]';
    this.Run_Anal = '(//span[text()="Run Analysis"])[1]';
    this.CSVlink = '//div[text()="Break-up"]//following::button[2]';
    this.Downloadcsv = '//div[text()="Break-up"]//following::button[3]';
    this.Top_Engagement_Signals = '[data-title="Top Engagement Signals"]';
    this.Select_Month = '//a[text()="Select Month"]';
    this.date_choosen = '//*[contains(@title,"01")]';
    this.Break_up = '//div[text()="Break-up"]';
    this.Breakup_Search = '//div[text()="Break-up"]//following::button[1]';
    this.Report_Name = '[placeholder="Report Name"]';
    this.Description_OP = '[placeholder="Description (Optional)"]';
    this.Closed = '(//span[text()="Close"])[1]';
    this.close_2 = '//span[text()="Close"]';
    this.Drafts = '//*[text()="Drafts"]';
    this.Saved_report_option = '//th[text()="Date"]//following::button[1]';
    this.Delete_Report = '//*[text()="Delete Report"]';
    this.Add_to_Dashboard = '//span[text()="Add to Dashboard"]';
    this.Please_Select = '//span[@class="ant-select-selection-placeholder"]';
    this.Automation_1 = '[title="Automation Dashboard"]';
    this.Automation_dashboard_Folder = '(//div[text()="Automation"])[1]'
    this.Automate = '//span[text()="Automation Dashboard"]';
    this.Automate_dashboard = '(//div[text()="Automation Dashboard"])[2]';
    this.Delete_Widget = '//a[text()="Delete Widget"]';
    this.Compare = '//*[text()="Compare"]';
    this.Compare_to = '//*[text()="Compare with:"]//following::li[2]';
    this.Hubspot_Companies = '[data-title="Hubspot Companies"]';
    this.Table_Body_1 = '.ant-table-content';
    this.Campaign_Groups = '//span[text()="Campaign Groups"]';
    this.Paid_search_visitors = '[placeholder="Eg- Paid search visitors"]';
    this.Account = '//*[text()="Accounts"]';
    this.Touchpoints = '//span[text()="Touchpoints Definitions"]';
    this.Hubspot_1 = '//span[text()="Hubspot"]';
    this.Salesforce = '//span[text()="Salesforce"]';
    this.Create_a_touchpoint_using_Contact = '//*[text()="Create a touchpoint using"]//following::button[1]';
    this.Campaigns = '[data-title="Campaigns"]';
    this.Add_Filter_1 = '//span[text()="Add Filter"]';
    this.Select_Type_Property = '(//div[text()="Select Type Property"])[1]';
    this.Select_Source_Property = '(//div[text()="Select Source Property"])[1]';
    this.Select_Campaign_Property = '(//div[text()="Select Campaign Property"])[1]';
    this.Select_Channel_Property = '(//div[text()="Select Channel Property"])[1]';
    this.Email_Tracking = '//span[text()="Email Tracking"]';
    this.Search_type = '//span[text()="Select Platform"]';
    this.Copy_Hubspot_UTM_Parameter = '//*[text()="Hubspot"]//following::button[1]';
    this.Add_Email_tracking = '//td[text()="User Email ID"]//following::button[1]';
    this.utm_tag = '#utm_tag';
    this.Verified_saved_UTM = '(//span[text()="Testing"][text()="{{contact.email}}"])[1]';
    this.X_close = '(//span[text()="Testing"])[1]/span';
    this.Open_Accenture_Acc = '//a[text()="accenture.com"]//following::button[1]';
    this.Page_view_validation = '.ant-drawer-body';
    this.Event_Properties = '//span[text()="Event Properties"]';
    this.Details = '(//span[contains(text(),"Linkedin")])[1]'
    this.Account_Executives = '//button[text()="Account Executives"]';
    this.This_is_correct = '//span[text()="This is correct"]';
    this.Performs_an_event = '[title="Performs an event"]';
    this.Enter_the_segment = '[title="Enter the segment"]';
    this.segment_name_2 = '//*[text()="Segment name"]//following::span[2]';
    this.In_Hubspot_text = '//div[text()="In Hubspot"]';
    this.Add_property_title = '[id=":r0:"]';
    this.Value = '#value';
    this.Date_Range = '#date_range';
    this.New_Filter = '//span[text()="New Filter"]';
    this.Select_Property_text = '//span[contains(text(),"Select Property")]';
    this.Name_text = '//span[text()="name"]';
    this.Create_new_alert_title = '//*[text()="Create new alert"]';
    this.Cancel = '(//span[text()="Cancel"])[1]';
    this.Remove_Property = '//span[text()="Remove Property"]';
    this.KPI_Report = '//*[text()="New KPI Report"]';
    this.KPI_Cal = '//span[text()="Run Analysis"]//preceding::button[1]';
    this.close_kpi = '#app-header > .justify-between > :nth-child(2) > .ant-btn-default > span';
    this.Share_to_slack = '//a[text()="Share to Slack"]';
    this.Share_to_slack_1 = '//span[text()="Share to Slack"]';
    this.slackShare_channel = '#slackShare_channel';
    this.alert_test_staging = '[title="#alert-test-staging"]';
    this.slackShare_message = '#slackShare_message';
    this.Email_this_report = '//a[text()="Email this report"]';
    this.emailShare_email = '#emailShare_email';
    this.emailShare_message = '#emailShare_message';
    this.Path_Analysis = '//*[text()="Path Analysis"]';
    this.Explain = '//*[text()="Explain"]';
    this.Path_Analysis_Pageload = ':nth-child(2) > .ant-col';
    this.Explain_pageload = '.ant-row > :nth-child(2)';
    this.Create_New_PathAna = '.ant-col-4 > .flex > .ant-btn';
    this.Start_with_an_event_title = '[title="Start with an event"]';
    this.Start_with_an_event = '//div[text()="Start with an event"]';
    this.Add_Event_1 = '(//span[text()="Add Event"])[1]';
    this.All_events_except_title = '[title="All events except"]';
    this.All_events_except = '//div[text()="All events except"]';
    this.Company_Created_title = '[data-title="Company Created"]';
    this.Steps = '//*[text()="Show"]//following::div[2]';
    this.Four_steps = 'div[title="4 Steps"]';
    this.Select_date_range = '//span[text()="Select date range"]';
    this.Preview_Month = '//input[@placeholder="Start date"]//following::button[4]';
    this.Start_Date = '(//div[text()="2"])[1]';
    this.End_Date = '(//div[text()="15"])[1]';
    this.Save_and_Build = '//span[text()="Save and Build"]';
    this.Basic_title = '[id="basic_title"]';
    this.Basic_description = '[id="basic_description"]';
    this.Building_Validation = '(//*[text()="Title"]//following::tr//td)[2]';
    this.Journey_Option = '//*[text()="Title"]//following::button[1]';
    this.Only_specific_events = '//div[text()="Only specific events"]';
    this.If_the_event_equals_title = '[title="If the event equals"]';
    this.If_the_event_equals = '//div[text()="If the event equals"]';
    this.Path_Select_event = '//*[text()="In this path, Show"]//following::input[3]';
    this.G2_Engagement_option = '//div[text()="Company Created"]';
    this.If_the_event_is_of_type = '//div[text()="If the event is of type"]';
    this.Path_Select_event_1 = '//*[text()="In this path, Show"]//following::input[5]';
    this.Page_Views = '[title="Page Views"]';
    this.Explain_CreateNew = '.justify-between > .ant-btn > span';
    this.Select_Analysis_Window = '.fa-custom-datepicker > .ant-btn';
    this.Hubspot_Contacts = '[data-title="Hubspot Contacts"]';
    this.Hubspot_Contacts1 = '[title="Hubspot Contacts"]';
    this.Contact_List_1 = '[data-title="Contact List"]';
    this.Profile_Report = '//*[text()="New Profile Report"]';
    this.Website_Visitors1 = '[title="Website Visitors"]';
    this.Filte_this_Profile = '//*[text()="PROFILES TO ANALYSE"]//following::button[3]';
    this.Delete_this_Profile = '//*[text()="PROFILES TO ANALYSE"]//following::button[4]';
    this.Add_Plus_button = '//button[contains(@class,"plus-button") and @index="0"]';
    this.BreakDown_AddNew = '//*[text()="BREAKDOWN"]//following::span[text()="Add new"]';
    this.Profile_report_gen = '.mt-12 > .justify-center';
    this.Country_Search_result = '(//div[text()="Company Country"]//following::tr)[2]/td[2]';
    this.Profile_Report_option = '//*[contains(text(),"Reports")]//following::button[1]';
    this.Add_to_Dashboard_title = '//*[text()="Add to Dashboard"]';
    this.Save_3 = '(//span[text()="Save"])[3]';
    this.Account_text = '//span[text()="Accounts"]';
    this.View_Report = '//a[text()="View Report"]';
    this.Expand_1 = '//span[text()="Expand"]';
    this.Save_dropdown = '//span[text()="Save"]//following::button[1]';
    this.Save_as_New = '//span[text()="Save as New"]';
    this.Delete_Report_1 = '(//a[text()="Delete Report"])[1]';
    this.Add_another_KPI_1 = '(//span[text()="Add another KPI"])[1]';
    this.Weekly_updates = '//h4[text()="Weekly updates"]';
    this.operator = '#operator';
    this.is_greater_than = '//div[text()="is greater than"]';
    this.Remove_Breakdown = '//*[text()="BREAKDOWN"]//following::button[2]';
    this.Remove_FilterBy = '//*[text()="FILTER BY"]//following::button[4]';
    this.Remove_FilterBy1 = '(//*[text()="FILTER BY"])[1]//following::button[4]';
    this.Overwrite = '//span[text()="Yes, overwrite it"]';
    this.InHubspot = '//span[text()="In Hubspot"]';
    this.workflow = "//div[text()='New Workflow']";
    this.Hubspot_template = '//input[@placeholder="Search"]//following::*[text()="Add or update HubSpot companies"]';
    this.Salesforce_template = '//input[@placeholder="Search"]//following::*[text()="Add or update Salesforce accounts"]';
    this.Use_this_template = '//span[text()="Use this workflow"]';
    this.workflow_edit_icon = '[aria-label="Edit"]';
    this.workflow_name = '//textarea[@class="ant-input"]';
    this.Configure_Action = '//span[text()="Configure Action"]';
    this.Website_activity = '[data-title="Website activity"]';
    this.Account_ID = '[title="Account ID"]';
    this.Deleted = '[title="Deleted"]';
    this.SaveandPublish = '(//span[text()="Save and Publish"])[1]';
    this.Remove_workflow = '//div[text()="Delete workflow"]';
    this.Search_dashboard = '[placeholder="Search dashboard"]';
    this.pageload_Confirmation = '#resizing-table-container-div';
    this.calender_Icon = '//div[@class="flex gap-x-1 items-center"]';
    this.ninety_days = '//li[contains(@data-menu-id,"90")]';
    this.form_Submissions = '//*[text()="Form Submissions"]';
    this.offer = '[data-title="Offer"]';
    this.campaign_title = '//main//div//div//h4[text()="Smart Reach"]';
    this.all_Accounts_Opt = '//h4[text()="All Accounts"]';
    this.hubspot_Cmpny_Opt = '//*[text()="Hubspot Companies"]';
    this.blinking_Check - '//td[@class="ant-table-cell"]//div//span//span[1]';
    this.confirm_Publish_Box = '//div[@class="ant-modal-body"]';
    this.global_Search = '//input[@placeholder="Search ⌘+K"]';
    this.global_Popup = '//div[contains(@class,"GlobalSearch__globalsearch-container")]';
    this.ask_Factors = '//span[text()="Ask Factors"]';
    this.ai_Textfield = '//input[@placeholder="Ask AI anything..."]';
    this.kpi_Heading = '//*[contains(text(),"Reports / KPI /")]';
    this.filter_By_Option = '//*[text()="FILTER BY"]';
    this.collapse_All = '//span[text()="Collapse all"]';
    this.Graph_Details = '//div[@class="mt-12"]';
    this.global_Jumpto = '//input[@placeholder="Search or jump to"]';
    this.segment_Page_Heading = '//*[text()="Untitled Segment 1"]';
    this.NewUsers = '[data-title="New Users"]';
    this.FilterthisKPI = '//*[text()="KPI TO ANALYSE"]//following::button[3]';
    this.companyRegion = '[title="Company Region"]';
    this.FilterthisKPI2 = '//*[text()="B"]//following::button[3]';
    this.KPI_Cal1 = '//*[text()="BREAKDOWN"]//following::button[4]';
    this.LastWeek = "//a[text()='Last Week']";
    this.userName = '[data-title="User Name"]';
    this.UserContinent = '[data-title="User Continent"]';
    this.KPI1Selected = '(//*[text()="A"])[1]//following::span[2]';
    this.FilterByName2 = '(//*[text()="where"])[2]//following::span[1]';
    this.FilterByName3 = '(//*[text()="where"])[1]//following::span[1]';
    this.KPI2Selected = '(//*[text()="B"])[1]//following::span[2]';
    this.KPI3Selected = '(//*[text()="C"])[1]//following::span[2]';
    this.CalenderCheck = '(//div[text()="from"])//following::button[1]';
    this.ChartCheck = '(//div[text()="from"])//following::span[2]';
    this.Metric = '//*[text()="Metric"]';
    this.EngagedUsers = '[data-title="Engaged Users"]';
    this.UserPostalCode = '[data-title="User Postal Code"]';
    this.FilterByName5 = '(//*[text()="and"])//following::span[1]';
    this.GlobalSearch = '[placeholder="Search ⌘+K"]';
    this.InternalSearch = '[placeholder="Search or jump to"]';
    this.SelectSavedReport = '//*[text()="Saved Reports"]//following::div[1]';
    this.KPIDashboard = '(//div[text()="All Boards"])[1]//following::span[2]';
    this.FirstKPIReport = '(//div[@id="card-1"]//h6)[1]';
    this.threedot_icon = '//div[@class="cursor-pointer"]//button';
    this.session_Medium_Option = '[data-title="Session Medium"]';
    this.filter_Funnel = '//div[@class="relative"]//button[@type="button"]';
    this.three_dot_create_Alias = '//*[text()="KPI TO ANALYSE"]//following::button[2]';
    this.create_Alias = '//span[text()="Create Alias"]';
    this.alias_Text_Field = '[placeholder="Alias title"]';
    this.create_Option = '//span[text()="Create"]';
    this.edit_Alias = '//span[text()="Edit Alias"]';
    this.update_Option = '//span[text()="Update"]';
    this.alias_Name_Verify = '//*[text()="KPI TO ANALYSE"]//following::h6[2]';
    this.previous_Day = '//*[text()="Previous Day"]';
    this.previous_30_Days = '//*[text()="Previous 30 Days"]';
    this.column = '//*[text()="Column"]';
    this.chart_Arrow = '(//div[@class="flex items-center gap-x-2"]//button[@type="button"]//*[local-name()="svg"])[4]';
    this.three_dot_Edit_Alias = '//*[text()="KPI TO ANALYSE"]//following::button[3]';
    this.not_Set_Option = '//b[text()="Not Set"]/..';
    this.datepicker1 = '(//div[@class="calendar"]//div[@class="fa-custom-datepicker"])[1]';
    this.datepicker2 = '(//div[@class="calendar"]//div[@class="fa-custom-datepicker"])[2]';
    this.cal_Selector = '//ul[@role="menu"]//li[6]';
    this.table_Check = '//div[@class="data-table"]';
    this.company_Industtry = '[data-title="Company Industry"]';
    this.company_option = '//*[text()="Company Identification"]';
    this.brkdwn_Cancel = '//*[text()="BREAKDOWN"]//following::button[2]';
    this.Add_Filters_value = '//*[text()="Company Identification"]';
    this.Add_Filters_value_searchbar = '(//span[text()="Select Property"]//following::input)[1]';
    this.Add_Filters_value1 = '//b[text()="Company Country ISO Code"]';
    this.Add_Event = '//*[text()="Add event"]';
    this.All_segments = '(//div[text()="All segments"])[1]';
    this.not_Set = '//div[@data-title="(Not Set)"]';
    this.New_folder = '//div[text()=" New Folder"]';
    this.create_newfolder = '//input[@placeholder="Eg- Folder 1"]';
    this.Edit_Folder = '//div[text()="Rename Folder"]';
    this.Delete_Folder = '(//div[text()=" Delete Folder"])[1]';
    this.confirmbtn = '//span[text()="Confirm"]';
    this.Folder_Delete = '//span[text()="Folder Deleted"]';
    this.delete_segment = '//div[text()="Delete segment"]';
    this.In_Hubspot = '//span[text()="In Hubspot"]';
    this.Last_Week = '//a[text()="Last Week"]';
    this.Account_currently = '//*[text()="Accounts currently in segment"]//following::span[1]';
    this.Account_high_engagement = '//*[text()="Accounts with High engagement"]//following::span[1]';
    this.Website_sessions = '//*[text()="Website sessions"]//following::span[1]';
    this.Total_Website_sessions = '//*[text()="% of total website sessions"]//following::span[1]';
    this.Total_visitor_segment = '//*[text()="Total visitors from segment"]//following::span[1]';
    this.Total_PageViews = '//*[text()="TotalPageViews"]//following::span[1]';
    this.Marketing_qualified = '(//*[text()="Marketing Engagement Analysis"]//following::span)[1]';
    this.sales_qualified = '(//*[text()="Sales Opportunity Analysis"]//following::span)[1]';
    this.Opportunity_Created = '//*[text()="Opportunity Created"]';
    this.Pipeline_Created = '//*[text()="Pipeline Created"]';
    this.Average_Deal_Size = '//*[text()="Average Deal Size"]';
    this.Revenue_Booked = '//*[text()="Revenue Booked"]';
    this.Close_Rate = '//*[text()="Close Rate (%)"]';
    this.Avg_Sales_Cycle_Length = '//*[text()="Avg Sales Cycle Length"]';
    this.Last_Month = '//a[text()="Last Month"]';
    this.Last_Quarter = '//a[text()="Last Quarter"]';
    this.select_custom_range = '//a[text()="Select Custom Range"]';
    this.Preview_Month1 = '//input[@placeholder="Start date"]//following::button[2]';
    this.Adpilot = '//*[text()="AdPilot"]';
    this.Add_new_rule = '//div[text()="Add New Rule"]';
    this.SyncNewAudience = '//div[text()="Sync New Audience"]';
    this.Campaign = '//*[text()="Campaign"]';
    this.select_Campaign = '//span[text()="Select Campaigns"]';
    this.select_Campaign_value = '//div[text()="TD-MessageAd-Conversions-MatchedAudience-US-0309"]';
    this.select_Campaign_value1 = '//div[text()="TD-Spotlight-WebsiteVisits-Gromo-0609"]';
    this.select_Campaign_value2 = '//div[text()="TD-MessageAds-WebsiteVisits-Gromo-0609"]';
    this.adpilot_arrow_left = '//*[local-name()="svg" and @data-icon="arrow-left"]';
    this.adpilot_publish = '//div[text()="Publish"]';
    this.Confirm_publish = '//span[text()="Publish"]';
    this.All_account_toogle = '//*[text()="Set custom rules based on advanced account conditions"]//preceding::button[1]';
    this.campaign_add_filter = '//*[text()="Add filter"]';
    this.total_clicks_cap = '(//th[text()="Total Clicks Cap"])[2]//following::input[1]';
    this.total_clicks_cap2 = '(//th[text()="Total Clicks Cap"])[2]//following::input[3]';
    this.total_clicks_cap3 = '(//th[text()="Total Clicks Cap"])[2]//following::input[4]';
    this.total_clicks_cap5 = '(//th[text()="Total Clicks Cap"])[2]//following::input[6]';
    this.total_clicks_cap6 = '(//th[text()="Total Clicks Cap"])[2]//following::input[7]';
    this.total_clicks_cap7 = '(//th[text()="Total Clicks Cap"])[2]//following::input[9]';
    this.delete = '//span[text()="Delete"]';
    this.discard_changes = '//div[text()="Discard Changes"]'; 
    this.advanced_custome_rule = '//*[text()="Set advanced custom rules"]//following::div[3]';
    this.campaign_group = '//*[text()="Campaign Group"]';
    this.select_campaign_group = '//span[text()="Select Campaign Groups"]';
    this.select_Campaigngroup_value = '//div[text()="BOFU - Matched Audience"]';
    this.select_Campaigngroup_value1 = '//div[text()="BOFU Prospecting"]';
    this.select_Campaigngroup_value2 = '//div[text()="TD-Prospecting-Gromo+Agencies"]';
    this.All_Ad_Account = '//*[text()="All Ad Accounts"]';
    this.pause = '//span[text()="Pause"]';
    this.confirm_publish = '//span[text()="Confirm Publish"]';
    this.Remove_rule = '//span[text()="Remove rule"]';
    this.segment_used = '(//div[contains(text(),"segments used")]//following::span)[1]';
    this.plans_billing = '(//h4[text()="Plans & Billing"])[1]';
    this.Upgrade = '//div[text()="Upgrade"]';
    this.Basic_add_btn = '(//h3[text()="Basic"]//following::button)[1]';
    this.Qty = '(//span[text()="Qty"])[1]';
    this.Qty1 = '(//span[text()="Qty"])[2]';
    this.Qty2 = '(//span[text()="Qty"])[3]';
    this.Qty3 = '(//span[text()="Qty"])[4]';
    this.Qty4 = '(//span[text()="Qty"])[5]';
    this.Qty_value = '(//div[contains(text(),"2")])[1]';
    this.Qty_value1 = '(//div[contains(text(),"2")])[2]';
    this.Qty_value2 = '(//div[contains(text(),"2")])[3]';
    this.Qty_value3 = '(//div[contains(text(),"2")])[4]';
    this.Qty_value4 = '(//div[contains(text(),"2")])[5]';
    this.proceed_to_checkout = '//span[contains(text(),"Proceed To Checkout")]';
    this.subscribe = '//span[contains(text(),"Subscribe")]';
    this.Growth_add_btn = '(//h3[text()="Growth"]//following::button)[1]';
    this.project_name = '//h4[text()="Kamali k"]//following::h4[text()="test 12345"]';
    this.user_name = '(//div[text()="kamali_tdfect@factors.ai"])[1]';
    this.project_name1 = '//h4[text()="Kamali k"]//following::h4[1]';
    this.switch = '//span[text()="Switch"]';
    this.Delete_segment = '//*[text()="Delete segment"]';
    this.select_event1 = '//input[@placeholder="Select Event"]//following::div[3]';
    this.select_factors_segment = '//th[text()="Factors segment to sync "]//following::span[1]';
    this.select_audiences_linkedin = '//th[text()="LinkedIn Audience to sync"]//following::input[2]';
    this.Engaged_linkedin = '//div[text()="Engaged on LinkedIn"]';
    this.Testing_audience = '//div[text()="Test audience | Third-party: Factors AI"]';
    this.Edit_workflow = '//a[text()="Edit"]';
    this.linkedin_sync_status = '//*[text()="LinkedIn Sync Status"]';
    this.remove_workflows = '//span[text()="Remove workflow"]';
    this.linkedin_refresh_icon = ".mr-1 > .ant-btn";
    this.test_capi = '(//div[text()="test capi"])[1]';
    this.First_Name = '(//span[text()="First Name"]//following::div)[4]';
    this.Last_Name = '(//span[text()="Last Name"]//following::div)[4]';
    this.Job_Tittle = '(//span[text()="Job Title"]//following::div)[4]';
    this.Company_Name = '(//span[text()="Company Name"]//following::div)[4]';
    this.Country_Code = '(//span[text()="Country Code"]//following::div)[4]';
    this.Add_a_Filter = '//span[text()="Add a filter"]';
    this.custom_event_name = '//*[contains(@class,"editable-title")]/button/span';
    this.All_segments1 = '(//span[text()="All Segments"])[1]';
    this.save_newfolder = '(//*[text()="Save"])[1]';
    this.Save_segments1 = '//span[text()="Save Segment "]';
    this.Apply_filter = '//span[text()="Apply filter"]';
    this.New_folder1 = '//span[text()="New folder"]';
    this.select_folder = "//span[text()='Please Select']";
    this.Search_Input = '(//input[@placeholder="Search"])[1]';
    this.Country_Breakdown = '[data-title="Company Country"]';
    this.Zoho_Templete = '//input[@placeholder="Search"]//following::*[text()="Add or update Zoho companies"]';
    this.Templete_Popup = '.ant-modal-content';
    this.PerformedEvent = '//*[text()="Account has performed event"]//following::span[2]';
    this.Select_Property = '(//*[text()="Additional fields (Optional)"]//following::input)[1]';
    this.Select_Property1 = '(//*[text()="Additional fields (Optional)"]//following::input)[2]';
    this.Select_Property2 = '(//*[text()="Additional fields (Optional)"]//following::input)[3]';
    this.Select_Property3 = '(//*[text()="Additional fields (Optional)"]//following::input)[4]';
    this.Selete_Property_Option = '[title="Email"]';
    this.Selete_Property_Option1 = '[data-title="Form ID"]';
    this.Form_ID1 = '[title="Form ID"]';
    this.AccountName = '[title="Account Name"]';
    this.AccountSite = '[title="Account Site"]';
    this.Save_Report = '(//*[text()="Save"])[3]';
    this.Campaign_MoreOption = '//*[text()="Active"]//following::button[2]';
    this.CreateNewSegment = '//span[text()="Create New Segment"]';
    this.active_Toggle1 = '//*[text()="Active"]//following::button[1]/div';
    this.FolderNameField = '[placeholder="Eg- Folder 1"]';
    this.PageView = '//span[text()="Page View"]';
    this.AddRule = '(//span[text()="Add rule"])[1]';
    this.Add_Rule2 = '//*[text()="Campaign details"]//following::span[text()="Add rule"]';
    this.Add_Rule3 = '//*[text()="G2 page details"]//following::span[text()="Add rule"]';
    this.HubSpotForms = '//span[text()="HubSpot Forms"]';
    this.PageUrlIs = '[title="Page URL is"]';
    this.PageUrlContains = '[title="Page URL contains"]';
    this.Formtitleis = '[title="Form title is"]';
    this.Formtitlecontains = '[title="Form title contains"]';
    this.SalesforceCampaigns = '//span[text()="Salesforce Campaigns"]';
    this.Campaignnameis = '[title="Campaign name is"]';
    this.Campaignnamecontains = '[title="Campaign name contains"]';
    this.LinkedInAds = '//span[text()="LinkedIn Ads"]';
    this.G2Intent = '//span[text()="G2 Intent"]';
    this.Pagetitleis = '[title="Page title is"]';
    this.Pagetitlecontains = '[title="Page title contains"]';
    this.URLoption = '((//div[@role="listbox"])[2]//following::div[6])[1]';
    this.SegmentTitle = '//*[contains(@class,"font-semibold editable-title")]';
    this.Touchpoints_Metaball = '(//tbody//tr//td[3]//button)[1]';
    this.DiscardandLeave = '(//span[text()="Discard and Leave"])[1]';
    this.StayonPage = '//span[text()="Stay on Page"]';
    this.BackArrow = '(//*[name()="svg" and @data-icon="arrow-left"])';
    this.Configurations = '//span[text()="Configurations"]';
    this.KPITOANALYSE = '//*[text()="KPI TO ANALYSE"]';
    this.EVENTS = '//*[text()="EVENTS"]';
    this.FUNNEL = '//*[text()="EVENTS PERFORMED IN"]';
    this.PROFILESTOANALYSE = '//*[text()="PROFILES TO ANALYSE"]';
    this.AllsegmentMenu = '(//*[text()="All segments"])[1]';
    this.Hubspot_InsightLoad = '//*[text()="In Hubspot"]//following::div[3]';
    this.NewAlert = '//span[text()="New Alert"]';
    this.StartfromScratch = '//span[text()="Start from Scratch"]';
    this.Hubspot_template_Option = '//button[text()="Hubspot"]';
    this.Salesforce_template_Option = '//button[text()="Salesforce"]';
    this.Zoho_template_Option = '//button[text()="Zoho"]';
    this.ChooseaTemplate = '//span[text()="Choose a Template"]';
    this.SelectTemplate = '//*[text()="One of your accounts just visited the pricing page"]';
    this.AddNewGroup = '//span[text()="Add New Group"]';
    this.SQLsandOpps = '[aria-label="SQLs and Opps"]';
    this.QuickSearchTitle = '(//div[@data-state="open"]/div/div/div/div)[1]';
    this.PreviewInfo = '.preview-info';
    this.DownloadCSV_Popup = '.ant-modal-content';
    this.SmartReach = '//h4[text()="Smart Reach"]';
    this.LinkedInaudiencesync = '//*[text()="LinkedIn audience sync"]';
    this.CustomEvents = '//span[text()="Custom Events"]';
    this.Filter = '//span[text()="Filter"]';
    this.channelGroup = '//span[text()="Channel Groups"]';
    this.EditProperty = '//a[text()="Edit Property"]';
    this.RemoveProperty = '//a[text()="Remove Property"]';
    this.panelemailTracking = '//*[text()="Email tracking"]';
    this.EmailClicks_container = '//div[contains(@class,"EmailClicks__container")]';
    this.Createatouchpointusing = '//*[text()="Create a touchpoint using"]';
    this.CampaignTitle = '//*[text()="New Custom Dimension"]';
    this.ValueName = '[placeholder="Value"]';
    this.NewSelectProperty = '//span[text()=" Select Property"]';
    this.NameOption = '[title="name"]';
    this.Filtervalue = '//*[text()="Filters"]//following::input[@type="text"]';
    this.Filtervalue1 = '(//*[text()="Filters"]//following::input[@type="text"])[2]';
    this.EditProperty1 = '//span[text()="Edit Property"]';
    this.PropertyMappingDisplayName = '#login_name';
    this.UserPlatform = '[title="User Platform"]';
    this.AlertMsg = '[role="alert"]';
    this.AdvancedFilters = '//h1[text()="Advanced Filters"]';
    this.HubspotDeals = '[data-title="Hubspot Deals"]';
    this.Deals = '[data-title="Deals"]';
    this.chartName = '(//*[local-name()="svg" and @id="funnel-grouped-svg-chart"])//following::div[1]';
    this.Removefromthisboard = '//div[text()="Remove from this board"]';
    this.LinkedInAdAccountField = '//*[text()="Select LinkedIn Ad Account"]//following::span[2]';
    this.LinkedInAdAccount = '[title="508934217"]';
    this.RenameSegment = '//div[text()="Rename segment"]';
    this.NewDashboard = '//span[text()="New Dashboard"]';
    this.WebsiteVisitorIdentification = '//*[text()="Website Visitor Identification"]';
    this.CopythisDashboard = '//span[text()=" Copy this dashboard "]';
    this.Report_Action = '//button[@id="fa-at-btn--new-report"]//following::button[1]';
    this.Movetofolder = '//div[text()="Move to folder"]';
    this.DeleteDashboard = '//div[text()="Delete dashboard"]';
    this.CreateCopy = '//div[text()="Create copy"]';
    this.AlertName = '//th[text()="Name"]//following::tbody/tr[1]/td[1]';
    this.ActivityLog = '//*[text()="Activity Log"]';
    this.HubspotCompany = '[data-title="Hubspot Company"]';
    this.HubspotDeal = '[data-title="Hubspot Deal"]';
    this.WebsiteSessionEvent = '//*[text()="Website Session"]';
    this.InsightMsg1 = '//img[@alt="loader-man"]//following::*[1]';
    this.InsightMsg2 = '//img[@alt="loader-man"]//following::*[2]';
    this.DeleteErrorPopup = '.ant-modal-title';
    this.Got_It = '//span[text()="Got it"]';
    this.ReportNameVerification = '//span[text()="Got it"]//preceding::div[1]';
    this.IntentPageLoaded = '//*[text()="Intent Upload"]';
    this.UploadIntentdata = '//*[text()="Upload third-party intent data"]';
    this.Date_Option = '//span[@title="Date of intent"]//following::input[1]';
    this.Source_Option = '//span[@title="Intent Source"]//following::input[1]';
    this.Domain_Option = '//span[@title="Company Domain"]//following::input[1]';
    this.Selectadditionalproperties = '//span[text()="Select additional properties"]';
    this.IntentDate = '[title="Intent Date"]';
    this.IntentCategory = '[title="Intent Category"]';
    this.Visittype = '[title="VIsit type - Intent drill down"]';
    this.Website1 = '[title="Website"]';
    this.Import = '//span[text()="Import"]';
    this.Error_Msg = '(//*[text()="This field needs to be mapped"])[1]';
    this.Import_Confirmation = '.ant-modal-confirm-title';
    this.OperationLog = '//*[text()="Operation Log"]';
    this.Logs = '//span[text()="Logs"]';
    this.OperationLog_Popup = '//*[text()="Operation Logs"]';
    this.Status_Verify = '//th[text()="File name"]//following::tr[1]/td[2]';
    this.Uploaded_By = '//th[text()="File name"]//following::tr[1]/td[3]';
    this.Intent_Download = '//th[text()="File name"]//following::tr[1]/td[5]';
    this.Choose_Template = '//*[text()="A new lead just submitted a form on your website"]';
    this.Mention_member = '//*[text()="Mentions"]//following::input[1]';
    this.sarath = '//div[text()="Sarath"]';
    this.EnterValue = '//span[text()="Enter Value"]';
    this.EnterValueInput = '[placeholder="Enter Value"]';
    this.HeyReach = '//button[text()="HeyReach"]';
    this.HeyReach_Template = '//div[@role="dialog"]//h4[text()="Add leads to a HeyReach list"]';
    this.IsoCode = '[data-title="Iso Code"]';
    this.IsoCode1 = '[title="Iso Code"]';
    this.API_Input = '#apollo_api_key';
    this.hey_reach_list_id = '#apollo_hey_reach_list_id';
    this.TestList = '[title="Test List"]';
    this.person_titles = '#apollo_person_titles';
    this.person_seniorities = '#apollo_person_seniorities';
    this.max_contacts = '#apollo_max_contacts';
    this.Smartlead = '//button[text()="Smartlead"]';
    this.SmartLead_Template = '//input[@placeholder="Search"]//following::h4[text()="Add leads to a Smartlead campaign"]';
    this.smartlead_campaign_id = '#apollo_smartlead_campaign_id';
    this.Dropdown = '[aria-label="down"]';
    this.Selectalldata = '//span[text()="Select all data"]';
    this.Invertcurrentpage = '//span[text()="Invert current page"]';
    this.Clearalldata = '//span[text()="Clear all data"]';
    this.pagination = '[rel="nofollow"]';
    this.property_name_list_selection = '(//div[@id="property_name_list"]//following::div[@title])[1]';
    this.Showmore = '//span[text()="Show more"]';
    this.UpdatethisSegment = '//span[text()="Update this Segment"]';
    this.SaveasNewSegment = '//span[text()="Save as New Segment"]';
    this.Apollo_Hubspot_Templete = '//input[@placeholder="Search"]//following::h4[text()="Add new contacts in HubSpot"]';
    this.Apollo_Salesforce_Templete = '//input[@placeholder="Search"]//following::h4[text()="Add new contacts in Salesforce"]';
    this.Apollo_Zoho_Templete = '//input[@placeholder="Search"]//following::h4[text()="Add new contacts in Zoho"]';
    this.Apollo_Select_Property = '(//h4[text()="Additional fields (for Company)"]//following::input)';
    this.ContactProperties = '//h4[text()="Select the contact properties you want to send"]//following::input';
    this.CompanyName = '[data-title="Company Name"]';
    this.City1 = '[title="City"]';
    this.Delete_Company = '//h4[text()="Additional fields (for Company)"]//following::button[2]';
    this.BillingCity1 = '[title="Billing City"]';
    this.ContactID = '[title="Contact ID"]';
    this.MasterRecordID = '[title="Master Record ID"]';
    this.LastName = '[title="Last Name"]';
    this.FirstName = '[title="First Name"]';
    this.Salutation = '[title="Salutation"]';
    this.FullName = '[title="Full Name"]';
    this.Search = '[type="search"]';
    this.AccountActivityURL = '[title="Account Activity URL"]';
    this.Assistant = '[title="Assistant"]';
    this.AsstPhone = '[title="Asst Phone"]';
    this.ContactImage = '[title="Contact Image"]';
    this.ContactOwner = '[title="Contact Owner"]';
    this.CreatedBy = '[title="Created By"]';
    this.DateofBirth = '[title="Date of Birth"]';
    this.Department = '[title="Department"]';
    this.Heyreach_campaign = '//div[@role="dialog"]//h4[text()="Add leads to a HeyReach campaign"]';
    this.hey_reach_campaign_id = '#apollo_hey_reach_campaign_id';
    this.TestCampaign = '[title="Test Campaign"]';
    this.hey_reach_sender_id = '#apollo_hey_reach_sender_id';
    this.senderID = '[title="Shubham Mathur"]';
    this.SetAlert = '//div[text()="Set Alert"]';
    this.Message = '#message';
    this.Exitthesegment = '[title="Exit the segment"]';
    this.Pagedetails = '//*[text()="Page details"]';
    this.AssignIndependentWeight = '//span[text()="Assign Independent Weight"]';
    this.IGScoreField1 = '(//*[name()="svg" and @data-icon="trash"])[1]//preceding::input[1]';
    this.IGScoreField2 = '(//*[name()="svg" and @data-icon="trash"])[2]//preceding::input[1]';
    this.Formsubmissiondetails = '//*[text()="Form submission details"]';
    this.IGCampaignsCampaignDetails = '//*[text()="Campaign details"]';
    this.G2pagedetails = '//*[text()="G2 page details"]';
    this.Eventdetails = '//*[text()="Event details"]';
    this.LinkedInCAPI = '//*[text()="LinkedIn CAPI"]';
    this.LinkedInCAPITitle = '//h4[text()="LinkedIn CAPI"]';
    this.SelectConversionEvent = '//*[text()="Map user properties"]//preceding::input[1]'
    this.TrafficDashboard = '//span[text()="Traffic Dashboard"]';
    this.TrafficDashboardTitle = '//h4[text()="Traffic Dashboard"]';
    this.TrafficAddFilter = '//h1[text()="Add" and text()=" filter"]';
    this.User = '[data-title="User"]';
    this.Applyfilters = '//span[text()="Apply filters"]';
    this.TrafficDashboardLoad = '//div[contains(@id,"card")]';
    this.TrafficViewFilter = '//h1[text()="View" and text()=" filter"]';
    this.Clearfilters = '//span[text()="Clear filters"]';
    this.AccountEngagementRules = '//div[text()="Account Engagement Rules"]';
    this.first_name1 = '[title="first_name"]';
    this.last_name = '[title="last_name"]';
    this.project_name_opt = '[title="project_name"]';
    this.Loader = '.accounts-loader-div';
    this.Loading = '[data-icon="loading"]';
    this.GlobalSearch_Loading = '//*[text()="loading..."]';
    this.UniqueUsers = '[data-title="Unique Users"]';
    this.AddProperty = '//span[text()="Add Property"]';
    this.SalesOpportunityAnalysis = '//*[text()="Sales Opportunity Analysis"]';
    this.FilterDataLoading = '//*[text()="Loading data..."]';
    this.SegmentTemplatePopup = '[role="dialog"]';
    this.Pipeline = '[data-title="Pipeline"]';
    this.HubspotDealDate = '[data-title="Hubspot Deal Owner Assigned Date"]';
    this.Inthecurrent = '[data-title="in the current"]';
    this.SelectBtn = '//button//span[text()="Select"]';
    this.Month = '[data-title="Month"]';
    this.ReportOptions = '//span[text()="Save"]//preceding::button[1]';
    this.EditDetails = '//span[text()="Edit Details"]';
    this.Yourmessage = '[placeholder="Your message"]';
    this.Emailthisreport = '//span[text()="Email this report"]';
    this.AddEmail = '//span[text()="Add Email"]';
    this.emailShare_email1 = '#emailShare_emails_0_email';
    this.Delete_Email = '//*[text()="Recipients"]//following::button[1]';
    this.SendEmailBtn = '//span[text()="Send Email"]';
    this.Realtimealerts = '//*[text()="Real time alerts"]';
    this.ShowLogs = '(//span[text()="Show Logs"])[1]';
    this.ActivityLog_Refresh = '//*[contains(text(),"Workflow runs for")]//following::button[1]';
    this.ActivityLog_Search = '//*[contains(text(),"Workflow runs for")]//following::button[2]';
    this.Searchreports = '[placeholder="Search reports"]';
    this.ActivityLog_SearchResult = '//*[text()="Activity Log"]//following::tbody/tr[1]/td[3]';
    this.ActivityLog_SearchClose = '//input[@placeholder="Search reports"]//following::button[1]';
    this.Alert_People = '//span[text()="People"]';
    this.Advancedsettings_Dropdown = '//*[text()="For the same value of"]//following::input[@type="search"]';
    this.Alert_PageTitle = '[name="$page_title"]';
    this.Alert_Scroll = '//*[text()="Where to get the alert"]';
    this.Alert_Toogle = '[role="switch"]';
    this.LinkedinDomain = '[data-title="Linkedin Domain"]';
    this.SmartReach_ViewActivitylog = '//div[text()="View Activity log"]';
    this.SmartReach_logTitle = '//*[text()="Account Change Log"]';
    this.SmartReach_logTable = '(//table)[2]';
    this.SmartReach_logClose = '//*[text()="Account Change Log"]//following::button[1]';
    this.SmartReach_logCalender = '//*[text()="Account Change Log"]//following::button[2]';
    this.SmartReach_Dashboard_log = '//span[text()="View Logs"]';
    this.New_Milestone_Btn = '//span[text()="Add Milestone"]';
    this.Milestone_Header = '//*[text()="Untitled Milestone"]';
    this.Milestones_Textarea1 = '//textarea[contains(@class,"ant-input")]';
    this.Journey_Filterthisevent = '//div[@id="additional_actions_events_block"]/button[1]';
    this.Add_Account_stage = '//span[text()="Add Account stage"]';
    this.Milestone_Limit = '//*[text()="Reached max number of account stages in a milestone"]';
    this.CopyMilestone_Btn = '((//div[@id="additional_actions_events_block"])[1]//preceding::button[3])[1]';
    this.DeleteMilestone_Btn = '((//div[@id="additional_actions_events_block"])[2]//preceding::button[2])[1]';
    this.Journey_Delete = '//div[text()="Delete"]';
    this.Journey_Clone = '//div[text()="Clone"]';
    this.Apollo_Person_locations = '#apollo_person_locations';
    this.Slack_Channel_List = '.rc-virtual-list-holder-inner';
    this.HeyReach_lead_list_Load = '[aria-label="loading"]';
    this.GoogleEnhancedConversions = '//*[text()="Google Enhanced Conversions"]';
    this.SyncNewConversion_Btn = '//div[text()="Sync New Conversion"]';
    this.SelectDealProperty = '//span[text()="Select Deal Property"]';
    this.PhoneNumber = '[title="Phone Number"]';
    this.UserEmailID = '[title="User Email ID"]';
    this.UserPhone = '[title="User Phone"]';
    this.Usethecustomvalue_Option = '[value="default_value"]';
    this.UsetheDealamount_Option = '[value="crm_deal_amount"]';
    this.Defaultconversionvalue_Input = '[placeholder="Default conversion value"]';
    this.ConversionfeedbackforLeads_Option = '[value="click"]';
    this.GoogleCAPIrules_Title = '//*[text()="Google CAPI rules"]';
    this.Google_Capi_Refresh_Btn = '//*[text()="Google CAPI rules"]//following::button[1]';
    this.Google_Capi_Search_Btn = '//*[text()="Google CAPI rules"]//following::button[2]';
    this.Google_Capi_TableRow_1 = '//tbody/tr[@data-row-key="0"]';
    this.Google_Capi_TableRow_2 = '//tbody/tr[@data-row-key="1"]';
    this.Google_Capi_FirstData = '//tbody/tr[@data-row-key="0"]/td[1]';
    this.Add_Additional_Property = '//span[text()="Add Additional Property"]';
    this.Multi_Select_Property = '//*[text()="Map properties from Factors to HubSpot"]//following::input[not(@disabled)]';
    this.Multi_Select_Property_Sales = '//*[text()="Map properties from Factors to Salesforce"]//following::input[not(@disabled)]';
    this.GEC_Refresh_Btn = '//button[text()="Try refreshing"]';
    this.Event_Select_a_property = '//span[text()="Select a property"]';
    this.datetime_objProperty = '#datetime_objProperty';
    this.datetime_objProperty_list = '//div[@id="datetime_objProperty_list"]//following::div[@title]';
    this.Event_Specific_change_in_property = '//span[text()="Specific change in property"]';
    this.PredictiveScoring = '//span[text()="Predictive Scoring"]';
    this.Newprediction = '//span[text()="New prediction"]';
    this.Predictionrule_Title = '//h6[text()="Set up Prediction rule"]';
    this.Run_a_check = '//span[text()="Run a check"]';
    this.Buildmodel = '//span[text()="Build model"]';
    this.PS_Add_Filter = '//div[@id="additional_actions_events_block"]/button[1]';
    this.Select_capping_level = '#fa-at-text--draft-title';
    this.AllAccount_ActionBtn = '//*[text()="All Accounts"]//following::button[1]';
    this.Show_hidden_accounts = '//div[text()="Show hidden accounts"]';
    this.Hide_hidden_accounts = '//div[text()="Hide hidden accounts"]';
    this.Event_Add_Property = '//*[text()="More Details"]//following::span[text()="Add property"]';
    this.Checkbox = '//tbody/tr/td[1]//input[@type="checkbox"]';
    this.Hide = '//span[text()="Hide"]';
    this.MovedSuccessfull_popup = '.ant-notification-notice-description';
    this.searchType = '#basic_accounts_search';
    this.Unhide = '//span[text()="Unhide"]';
    this.Unhide_1 = '(//span[text()="Unhide"])[2]';
    this.Hubspot_Deal_Opt = '[data-title="Hubspot Deal Record ID"]';
    this.Additional_Select_Property = '(//span[text()="Add Additional Property"])[1]//preceding::input[@type="search"]';
    this.Delete_Map_properties = '//h4[text()="Map properties from Factors to Salesforce"]//following-sibling::div//button[not(@disabled)]';
    this.ViewHiddenAccounts_Link = '//span[text()="View Hidden Accounts"]';
    this.Select_Events_to_Show = '[placeholder="Select Events to Show"]';
    this.segment_summary_Icon = '//*[local-name()="svg" and @data-icon="envelope"]';
    this.receive_this_digest_Input = '[placeholder="yourmail@gmail.com"]';
    this.Digest_Tooltip = '.ant-alert-message';
    this.Remove_Digest_Mail = '//*[local-name()="svg" and @data-icon="xmark"]';
    this.SelectaDay = '#frequency_day';
    this.Email_Limit_ToolTip = '//div[contains(text(),"Maximum limit of") and contains(text(),"10") and contains(text(),"email recipients reached")]';
    this.Mail_Day = '[title="Wednesday"]';
    this.SelectTime = '#frequency_time';
    this.Mail_Time = '[title="02:30 PM"]';
    this.Digest_properties = '//span[text()="Paid Search Visitors"]';
    this.Alert_Update_Btn = '//div[text()="Update"]';
    this.Alert_Hide_Option = '//a[text()="Hide advanced options"]';
    this.properties_list_Option = '//div[@id="properties_list"]//following::div[@title]';
    this.Subscribe_Digest_Btn = '//span[text()="Subscribe Digest"]';
    this.Manage_Subscription = '//div[text()="Manage Subscription"]';
    this.Send_a_test_email = '//span[text()="Send a test email "]';
    this.Sharing = '//span[text()="Sharing"]';
    this.Segment_Digest = '//span[text()="Segment Digest"]';
    this.Set_Up_Segment_Digest_Header = '//span[text()="Set Up Segment Digest"]';
    this.Enter_Segment_Input = '#segment';
    this.Segment_Digest_Edit_Btn = '//span[text()="Edit"]';
    this.Manage_Segment_Digest_Header = '//span[text()="Manage Segment Digest"]';
    this.Delete_Digest = '//span[text()="Delete Digest"]';
    this.Yes_Delete = '//span[text()="Yes, Delete"]';
    this.Factors_Icon = '#fa-at-link--home';
    this.Subscribe_Digest_Segment = '[data-icon="envelope-circle-check"]';
    this.Google_Conversion_Action_Dropdown_Option = '//div[@class="rc-virtual-list-holder"]//div[@title]';
    this.Rename_Signal_Popup = '//h4[text()="Rename Signal"]';
    this.ES_Rename_InputField = '[placeholder="Title"]';
    this.alertteststaging = '//div[text()="alert-test-staging"]';
    this.Select_Channel1 = '//*[contains(text(), "select the channels")]//following::input[@role="combobox"][1]';
    this.SelectClick = "//input[@type='search' and @aria-expanded='true']";
    this.Select_Values = '//span[text()="Select values"]';
    this.Select_Events_to_show = '[placeholder="Select Events to Show"]';
    this.Event_Based = '[title="Event Based"]';
    this.Function = '#event_function';
    this.Unique = '[title="Unique"]';
    this.Time_of_Occurrence = '[data-title="Time Of Occurrence"]';
    this.Day_of_Occurrence = '[data-title="Day Of Occurrence"]';
    this.KPI_Category = '#kpi_category';
    this.KPI_Function = '#kpi_function';
    this.Average = '[title="Average"]';
    this.Time_Period_Based = '[title="Time Period Based"]';
    this.Add = '//span[normalize-space()="Add"]';
    this.Date_Field = '//*[text()="Set time to"]//following::span[1]';
    this.First_Seen_Date = '[data-title="First Seen Date"]';
    this.First_Seen_Date1 = '[title="First Seen Date"]';
    this.KPI_Type = '(//div[@class="ant-select-selector"]//following::span)[1]';
    this.Function_1 = '//input[@type="search"]//following::span[text()="Function"]';
    this.data_icon = '[data-icon="download"]';
    this.table_columns = '[data-icon="table-columns"]';
    this.Not_Customers = '[aria-label="Not Customers"]';
    this.Bolt = '(//span[text()="Edit Segment"]//following::button)[1]';
    this.LinkedIn_Audience_Sync1 = '//*[text()="LinkedIn Audience Sync"]';
    this.Search_Properties = '[placeholder="Search Properties"]';
    this.Edit_Segment = '//span[text()="Edit Segment"]';
    this.Insight_Icon = '[data-icon="lightbulb-on"]';
    this.In_Hubspot3 = '//h4[text()="In Hubspot"]';
    this.Staging_app_factors = '[title="https://staging-app.factors.ai/explain"]';
    this.Add_Contacts = '[title="SSO_Non_SDK (Naveena) - copy"]';
    this.Prevoius_Month = '.ant-picker-header-prev-btn';
    this.Month_Date = '//div[@class="ant-picker-body"]//following::div[text()="17"]';
    this.Funnel_Breakdown = '//*[text()="EVENTS PERFORMED IN"]//following::button[3]';
    this.Channel_PlusIcon = '(//*[text()="where"]//following::button)[4]';
    this.between = '[data-title="between"]';
    this.Search_or_jump = '[placeholder="Search or jump to"]';
    this.Create_New_Event_Report = '//span[text()="Create New Event Report"]';
    this.Close_without_saving = '//span[text()="Close without saving"]';
    this.Create_New_Funnel_Report = '//span[text()="Create New Funnel Report"]';
    this.Create_New_Profile_Report = '//span[text()="Create New Profile Report"]';
    this.Create_New_KPI_Report = '//span[text()="Create New KPI Report"]';
    this.Created_Since = '//*[text()="Created Since"]//following::button[1]';
    this.Yes_proceed = '//span[text()="Yes, proceed"]';
    this.Open_Filter = '[data-state="open"]';
    this.Title_page = '//*[contains(@class,"editable-title")]';
    this.Company_Region = '[data-id="Company Region"]';
    this.Views_tab = '//button[contains(@class,"ant-popover-open")]';
    this.Hubspot_Deals1 = '[title="Hubspot Deals"]';
    this.Create_Date = '[title="Hubspot Deal Create Date"]';
    this.Show_More = '//span[text()="Show More"]';
    this.Contact_Updated = '[data-title="Contact Updated"]';
    this.Person_Matches = '.ant-collapse-content-box';
    this.User_Total_Active_Time = '[data-title="User Total Active Time"]';
    this.Hubspot_Contact_Record_ID = '[data-title="Hubspot Contact Record ID"]';
    this.Show_Alert_Every = '//div[@class="rc-virtual-list-holder-inner"]/div[1]';
    this.Third_party_Intent_Visit = '[data-title="Third Party Intent Visit"]';
    this.Accounts_active_on_website = '//*[text()="Accounts active on website but did not view a LinkedIn Ad in the last 30 days"]//following::span[1]';
    this.Engagement_Email = '[data-title="Engagement Email"]';
    this.Data_Management = '//span[text()="Data Management"]';
    this.Account_Configurations_1 = '//span[text()="Account Configurations"]';
    this.Project_Settings = '//span[text()="Project Settings"]';
    this.Custom_Definitions_1 = '//span[text()="Custom Definitions"]';
    this.Property_Mapping = '//span[text()="Property Mapping"]';
    this.Engagement_Scoring = '//span[text()="Engagement Scoring"]';
    this.Interest_Groups = '//span[text()="Interest Groups"]';
    this.Custom_KPI = `//span[text()="Custom KPIs"]`;
    this.New_Custom_KPI = '//*[text()="New Custom KPI"]';
    this.Hidden_Accounts1 = '//span[text()="Hidden Accounts"]';
    this.Intent_upload = '//span[text()="Intent Upload"]';
    this.Integrations1 = '//h4[text()="Integrations"]';
    this.Session_Count = '[data-title="Session Count"]';
    this.Moved_To_HiddenAccounts_Close = '.ant-notification-notice-close-x';
    this.Hubspot_Deal_Sales_Owner = '[data-title="Hubspot Deal Sales Owner"]';
    this.Hubspot_Contact_Pipeline = '[data-title="Hubspot Contact Pipeline"]';
    this.Hubspot_Company_URL = '[data-title="Hubspot Company URL"]';
    this.DataManagementHeader = '//h4[contains(@class,"text-base font-normal")]';
    this.Account_identification1 = '//h6[text()="Account identification"]';
    this.Milestone_Title_Name = '//textarea[text()="Untitled Milestone"]';
    this.Edit_Button = '[data-icon="pen"]';
    this.Linkedin_Paid_Leads = '[data-title="Linkedin Paid Leads"]';
    this.Company_Created1 = '//h6[text()="Company Created"]';
    this.Engaged_Sessions = '[data-title="Engaged Sessions"]';
    this.Company_Type = '[data-id="Company Type"]';
    this.Members_Roles = '//span[text()="Members & Roles"]';
    this.SEGMENT_SUMMARY_UPDATE = '[data-title="SEGMENT_SUMMARY_UPDATE"]';
    this.Hubspot_Contact_IP_Country_Code = '[data-title="Hubspot Contact IP Country Code"]';
    this.Hubspot_Deal_Trumpet_Total_Views = '[data-title="Hubspot Deal Trumpet Total Views"]';

  }
}

export default new locators();