import Login1 from '../../PageObjects/Login1';
import methods from '../../../support/Common_Method.js';
import { deviceViewport, extraTimeOut, Timeout } from '../../Utils.js';
import locators from '../../../support/Locators.js';
import dayjs from 'dayjs';

const nowTime = dayjs().format('H:m:s');
const new_campaign = `New Campaign Pause_${nowTime}`;

describe('Adpilot Smart reach', () => {

    beforeEach(() => {

        cy.viewport(deviceViewport);

        cy.on('uncaught:exception', (err, runnable) => {
            return false;
        });

        //login before run test
        Login1();

    })

    it('Adpilot Smart reach Campaign - To Add , Edit Rule , Publish Rule and Delete Rule', () => {

        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Campaign_${nowTime}`;
        const new_campaign1 = `New Campaign_${nowTime}_1`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        cy.xpath('(//tbody/tr/td)[1]')
            .invoke('text')
            .then((text) => {
                cy.wrap(text.trim()).as('Text1');
            });
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.xs)
        methods.VisibilityofElementIndexInput(locators.Select_capping_level, 0)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.select_Campaign)
        methods.clickElementByXPath(locators.select_Campaign_value)
        methods.clickElementByXPath(locators.select_Campaign_value1)
        methods.clickElementByXPath(locators.select_Campaign_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        cy.get('@Text1').then((Text1) => {
            methods.ClearAndTypeWithXpath(locators.workflow_name, Text1);
        });
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup2, "Failed!duplicate name")
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, new_campaign)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(`//h4[text()="${new_campaign}"]//following::td[1]`, "Active")
        methods.clickElementByXPath(`//h4[text()="${new_campaign}"]`)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, new_campaign1)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "500")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap3, "500")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap5, "3")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap6, "500")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap7, "3")
        cy.wait(Timeout.sm)
        methods.ScrollAndClickxpath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Updated!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(`//h4[text()="${new_campaign1}"]//following::td[1]`, "Active")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()="${new_campaign1}"]//following::button[1]`)
        methods.clickElementByXPath(locators.Remove_rule)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('Adpilot Smart reach To discard the changes made', () => {
        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Campaign_${nowTime}`;
        const new_campaign1 = `New Campaign_${nowTime}_1`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.xs)
        methods.VisibilityofElementIndexInput(locators.Select_capping_level, 0)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.select_Campaign)
        methods.clickElementByXPath(locators.select_Campaign_value)
        methods.clickElementByXPath(locators.select_Campaign_value1)
        methods.clickElementByXPath(locators.select_Campaign_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(`//h4[text()="${new_campaign}"]//following::td[1]`, "Active")
        methods.clickElementByXPath(`//h4[text()="${new_campaign}"]`)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, new_campaign1)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "500")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.clickElementByXPath(locators.discard_changes)
        methods.NotVisibilityofElementXpath(locators.advanced_custome_rule)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.delete)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('Adpilot Smart reach Campaign Group - To Add , Edit Rule , Publish Rule, and delete Rule', () => {
        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Group Campaign_${nowTime}`;
        const new_campaign1 = `New Group Campaign_${nowTime}_1`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        cy.xpath('(//tbody/tr/td)[1]')
            .invoke('text')
            .then((text) => {
                cy.wrap(text.trim()).as('Text1');
            });
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.xs)
        methods.VisibilityofElementIndexInput(locators.Select_capping_level, 0)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.campaign_group)
        methods.clickElementByXPath(locators.select_campaign_group)
        methods.clickElementByXPath(locators.select_Campaigngroup_value)
        methods.clickElementByXPath(locators.select_Campaigngroup_value1)
        methods.clickElementByXPath(locators.select_Campaigngroup_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        cy.get('@Text1').then((Text1) => {
            methods.ClearAndTypeWithXpath(locators.workflow_name, Text1);
        });
        methods.clickElementByXPath(locators.campaign_group)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup2, "Failed!duplicate name")
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, new_campaign)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(`//h4[text()="${new_campaign}"]//following::td[1]`, "Active")
        methods.clickElementByXPath(`//h4[text()="${new_campaign}"]`)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, new_campaign1)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "1000")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap3, "1000")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap5, "3")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap6, "1000")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap7, "3")
        cy.wait(Timeout.sm)
        methods.ScrollAndClickxpath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Updated!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(`//h4[text()="${new_campaign1}"]//following::td[1]`, "Active")
        methods.clickElementByXPath(`//h4[text()="${new_campaign1}"]//following::button[1]`)
        methods.clickElementByXPath(locators.Remove_rule)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('Adpilot Smart reach To discard the changes made - Campaign group', () => {
        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Group Campaign_${nowTime}`;
        const new_campaign1 = `New Group Campaign_${nowTime}_1`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.xs)
        methods.VisibilityofElementIndexInput(locators.Select_capping_level, 0)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.campaign_group)
        methods.clickElementByXPath(locators.select_campaign_group)
        methods.clickElementByXPath(locators.select_Campaigngroup_value)
        methods.clickElementByXPath(locators.select_Campaigngroup_value1)
        methods.clickElementByXPath(locators.select_Campaigngroup_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.clickElementByXPath(locators.campaign_group)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()="${new_campaign}"]`)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, new_campaign1)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "1000")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.clickElementByXPath(locators.discard_changes)
        methods.NotVisibilityofElementXpath(locators.advanced_custome_rule)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.delete)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('Adpilot Smart reach All ad accounts - To Add , Edit Rule , Publish Rule, and delete Rule', () => {
        const nowTime = dayjs().format('H:m:s');
        const Add_campaign = `All Ad Accounts_${nowTime}`;
        const Add_campaign1 = `All Ad Accounts_${nowTime}_1`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        cy.xpath('(//tbody/tr/td)[1]')
            .invoke('text')
            .then((text) => {
                cy.wrap(text.trim()).as('Text1');
            });
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.xs)
        methods.VisibilityofElementIndexInput(locators.Select_capping_level, 0)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_editicon)
        cy.get('@Text1').then((Text1) => {
            methods.ClearAndTypeWithXpath(locators.workflow_name, Text1);
        });
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup2, "Failed!duplicate name")
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, Add_campaign)
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()="${Add_campaign}"]`)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, Add_campaign1)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "1000")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap3, "1000")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap5, "3")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap6, "1000")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap7, "3")
        cy.wait(Timeout.sm)
        methods.ScrollAndClickxpath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Updated!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(`//h4[text()="${Add_campaign1}"]//following::td[1]`, "Active")
        methods.clickElementByXPath(`//h4[text()="${Add_campaign1}"]//following::button[1]`)
        methods.clickElementByXPath(locators.Remove_rule)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('Adpilot Smart reach To discard the changes made  - All ad accounts', () => {
        const nowTime = dayjs().format('H:m:s');
        const Add_campaign = `All Ad Accounts_${nowTime}`;
        const Add_campaign1 = `All Ad Accounts_${nowTime}_1`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        cy.xpath('(//tbody/tr/td)[1]')
            .invoke('text')
            .then((text) => {
                cy.wrap(text.trim()).as('Text1');
            });
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.xs)
        methods.VisibilityofElementIndexInput(locators.Select_capping_level, 0)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_editicon)
        cy.get('@Text1').then((Text1) => {
            methods.ClearAndTypeWithXpath(locators.workflow_name, Text1);
        });
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup2, "Failed!duplicate name")
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, Add_campaign)
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()="${Add_campaign}"]`)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, Add_campaign1)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        methods.clickElement(locators.equals_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "1000")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.clickElementByXPath(locators.discard_changes)
        methods.NotVisibilityofElementXpath(locators.advanced_custome_rule)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.delete)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('Adpilot Smart reach To verify whether the pause functionality is working has expected', () => {

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.xs)
        methods.VisibilityofElementIndexInput(locators.Select_capping_level, 0)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.select_Campaign)
        methods.clickElementByXPath(locators.select_Campaign_value)
        methods.clickElementByXPath(locators.select_Campaign_value1)
        methods.clickElementByXPath(locators.select_Campaign_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()="${new_campaign}"]`)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.active_Toggle1)
        methods.clickElementByXPath(locators.pause)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Updated!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.xs)
        methods.assertElementContainsText1(`//h4[text()="${new_campaign}"]//following::span[1]`, "Paused")
        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.SmartReach)
        methods.assertElementContainsTextxpath(locators.SmartReach, 'Smart Reach')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Enable_button)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.confirm_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Updated!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        methods.assertElementContainsText1(`//h4[text()="${new_campaign}"]//following::span[1]`, "Active")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()="${new_campaign}"]`)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.delete)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('Adpilot Smart Reach - View Activity Logs', () => {
        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Campaign Logs_${nowTime}`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElementXpath(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.xs)
        methods.VisibilityofElementIndexInput(locators.Select_capping_level, 0)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.select_Campaign)
        methods.clickElementByXPath(locators.select_Campaign_value)
        methods.clickElementByXPath(locators.select_Campaign_value1)
        methods.clickElementByXPath(locators.select_Campaign_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.SmartReach_ViewActivitylog)
        methods.VisibilityofElementXpath(locators.SmartReach_logTitle)
        methods.VisibilityofElementXpath(locators.SmartReach_logTable)
        methods.clickElementByXPath(locators.SmartReach_logCalender)
        methods.clickElementByXPath(locators.Last_Month)
        methods.VisibilityofElementXpath(locators.SmartReach_logTitle)
        methods.clickElementByXPath(locators.SmartReach_logClose)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(`//h4[text()="${new_campaign}"]//following::td[1]`, "Active")
        methods.clickElementByXPath(`//h4[text()="${new_campaign}"]//following::button[1]`)
        methods.clickElementByXPath(locators.SmartReach_Dashboard_log)
        methods.VisibilityofElementXpath(locators.SmartReach_logTitle)
        methods.VisibilityofElementXpath(locators.SmartReach_logTable)
        methods.clickElementByXPath(locators.SmartReach_logCalender)
        methods.clickElementByXPath(locators.Last_Month)
        methods.VisibilityofElementXpath(locators.SmartReach_logTitle)
        methods.clickElementByXPath(locators.SmartReach_logClose)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()="${new_campaign}"]//following::button[1]`)
        methods.clickElementByXPath(locators.Remove_rule)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")

    })
})