import { APIKEY, deviceViewport, extraTimeOut, Timeout } from '../../Utils.js';
import envDetails from '../../../fixtures/envDetails.json';
import methods from '../../../support/Common_Method.js';
import locators from '../../../support/Locators.js';
import dayjs from 'dayjs';
import Login1 from '../../PageObjects/Login1.js';


describe('Apollo Login', () => {

    beforeEach(() => {

        cy.viewport(deviceViewport);

        cy.on('uncaught:exception', (err, runnable) => {
            return false;
        });

        //login before run test
        Login1();

    })

    it.skip('Apollo - Hubspot', () => {

        const nowTime = dayjs().format('H:m:s');
        const testName = `Demo Apollo Hubspot ${nowTime}`;
        const testName1 = `Demo Apollo Hubspot New ${nowTime}_1`;
        const IntegrateName = "HubSpot";

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        cy.visit(`${envDetails.backendApiUrl}/automations/workflows`)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(locators.workflows_Title, 'Workflows')
        methods.VisibilityofElement(locators.identi_table)
        cy.wait(Timeout.xs)
        methods.ElementToBeClickableXpath(locators.workflow)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.workflow)
        methods.clickElementByXPath(locators.Hubspot_template_Option)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Apollo_Hubspot_Templete)
        methods.clickElementByXPath(locators.Use_this_template)
        methods.clickElementByXPath(locators.select_event)
        methods.clickElement0(locators.others1, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Configure_Action)
        cy.wait(Timeout.md)
        methods.ScrollAndClickxpath(locators.adpilot_arrow_left)
        methods.ElementToBeClickableXpath(locators.workflow)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.workflow)
        methods.clickElementByXPath(locators.Hubspot_template_Option)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Apollo_Hubspot_Templete)
        methods.clickElementByXPath(locators.Use_this_template)
        methods.clickElement(locators.workflow_edit_icon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, testName)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.select_event)
        methods.clickElement0(locators.others1, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Configure_Action)
        cy.wait(Timeout.md)
        methods.VisibilityofElementXpath(`//h4[text()="Map properties from Factors to ${IntegrateName}"]`)
        methods.typeElement(locators.API_Input, APIKEY)
        cy.wait(Timeout.sm)
        methods.Enter(locators.API_Input)
        cy.wait(Timeout.xs)
        methods.scrollWithXpath(locators.SaveandPublish)
        methods.typeElement(locators.person_titles, "Testing")
        methods.typeElement(locators.person_seniorities, "Testing")
        methods.typeElement(locators.Apollo_Person_locations, "India")
        methods.typeElement(locators.max_contacts, "10")
        cy.wait(Timeout.xs)
        methods.clickElementIndexXpath(locators.Add_Additional_Property, 1)
        methods.clickElementByXPath(locators.Multi_Select_Property)
        methods.typeElementByXPath(locators.Multi_Select_Property, "full")
        methods.clickElement(locators.FullName)
        methods.clickElementIndexXpath(locators.Multi_Select_Property, 1)
        methods.typeElementByXPathwithIndex(locators.Multi_Select_Property, "first na", 1)
        methods.clickElement(locators.FirstName)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.SaveandPublish)
        methods.GetText(locators.notification_popup, "Workflow SavedNew workflow is created and saved successfully.")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()='${testName}']`)
        methods.clickElement(locators.workflow_edit_icon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, testName1)
        methods.EnterXpath(locators.workflow_name)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Add_a_Filter)
        methods.clickElement0(locators.Hubspot_Contacts, 0)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        cy.wait(Timeout.sm)
        methods.clickElement(locators.equals_1)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        cy.wait(Timeout.xs)
        methods.scrollWithXpath(`//h4[text()="Map properties from Factors to ${IntegrateName}"]`)
        methods.VisibilityofElementXpath(`//h4[text()="Map properties from Factors to ${IntegrateName}"]`)
        methods.scrollWithXpath(locators.SaveandPublish)
        methods.clickElementIndexXpath(locators.Add_Additional_Property, 0)
        methods.clickElementIndexXpath(locators.Multi_Select_Property, 0)
        methods.typeElementByXPathwithIndex(locators.Multi_Select_Property, "region", 0)
        methods.clickElement(locators.companyRegion)
        methods.clickElementIndexXpath(locators.Multi_Select_Property, 1)
        methods.typeElementByXPathwithIndex(locators.Multi_Select_Property, "city", 1)
        methods.clickElement(locators.City1)
        cy.wait(Timeout.xs)
        methods.ScrollAndClickxpath(locators.SaveandPublish)
        methods.GetText(locators.notification_popup, "Workflow UpdatedWorkflow is updated and saved successfully.")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()='${testName1}']//following::button[2]`)
        methods.clickElementByXPath(locators.Remove_workflow)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.GetText(locators.notification_popup, "SuccessDeleted Workflow successfully")
        cy.wait(Timeout.xs)

    })

    it.skip('Apollo - Salesforce', () => {

        const nowTime = dayjs().format('H:m:s');
        const testName = `Demo Apollo Salesforce ${nowTime}`;
        const IntegrateName = "Salesforce";

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        cy.visit(`${envDetails.backendApiUrl}/automations/workflows`)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(locators.workflows_Title, 'Workflows')
        methods.VisibilityofElement(locators.identi_table)
        cy.wait(Timeout.xs)
        methods.ElementToBeClickableXpath(locators.workflow)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.workflow)
        methods.clickElementByXPath(locators.Salesforce_template_Option)
        methods.clickElementByXPath(locators.Apollo_Salesforce_Templete)
        methods.clickElementByXPath(locators.Use_this_template)
        methods.ScrollAndClickxpath(locators.adpilot_arrow_left)
        methods.ElementToBeClickableXpath(locators.workflow)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.workflow)
        methods.clickElementByXPath(locators.Salesforce_template_Option)
        methods.clickElementByXPath(locators.Apollo_Salesforce_Templete)
        methods.clickElementByXPath(locators.Use_this_template)
        methods.clickElement(locators.workflow_edit_icon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, testName)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.select_event)
        methods.clickElement0(locators.others1, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Configure_Action)
        cy.wait(Timeout.xmd)
        methods.VisibilityofElementXpath(`//h4[text()="Map properties from Factors to ${IntegrateName}"]`)
        cy.wait(Timeout.xs)
        methods.clickElementIndexXpath(locators.Add_Additional_Property, 0)
        methods.clickElementIndexXpath(locators.Additional_Select_Property, 1)
        methods.typeElementByXPathwithIndex(locators.Additional_Select_Property, "top", 1)
        methods.clickElement(locators.TopEngagementSignal)
        methods.clickElementIndexXpath(locators.Additional_Select_Property, 0)
        methods.typeElementByXPathwithIndex(locators.Additional_Select_Property, "Billing", 0)
        methods.clickElement(locators.BillingCity1)
        cy.wait(Timeout.xs)
        methods.typeElement(locators.API_Input, APIKEY)
        methods.scrollWithXpath(locators.SaveandPublish)
        methods.typeElement(locators.person_titles, "Testing")
        methods.typeElement(locators.person_seniorities, "Testing")
        methods.typeElement(locators.Apollo_Person_locations, "India")
        methods.typeElement(locators.max_contacts, "10")
        methods.clickElementIndexXpath(locators.ContactProperties, 1)
        methods.clickElement0(locators.ContactID, 0)
        methods.clickElementIndexXpath(locators.ContactProperties, 3)
        methods.clickElement0(locators.Deleted, 1)
        methods.clickElementIndexXpath(locators.ContactProperties, 5)
        methods.clickElement0(locators.MasterRecordID, 2)
        methods.clickElementIndexXpath(locators.ContactProperties, 7)
        methods.clickElement0(locators.Account_ID, 3)
        methods.clickElementIndexXpath(locators.ContactProperties, 9)
        methods.clickElement0(locators.LastName, 4)
        methods.clickElementIndexXpath(locators.ContactProperties, 11)
        methods.clickElement0(locators.FirstName, 5)
        methods.clickElementIndexXpath(locators.ContactProperties, 13)
        methods.clickElement0(locators.Salutation, 6)
        methods.clickElementIndexXpath(locators.ContactProperties, 15)
        methods.clickElement0(locators.FullName, 8)
        methods.clickElementByXPath(locators.SaveandPublish)
        methods.GetText(locators.notification_popup, "Workflow SavedNew workflow is created and saved successfully.")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()='${testName}']`)
        methods.clickElementByXPath(locators.Add_a_Filter)
        methods.clickElement0(locators.Hubspot_Contacts, 0)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        cy.wait(Timeout.sm)
        methods.clickElement(locators.equals_1)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        cy.wait(Timeout.xs)
        methods.ScrollAndClickxpath(locators.Delete_Map_properties)
        cy.wait(Timeout.xs)
        methods.NotExistxpath(locators.Delete_Map_properties)
        cy.wait(Timeout.xs)
        methods.ScrollAndClickxpath(locators.SaveandPublish)
        methods.GetText(locators.notification_popup, "Workflow UpdatedWorkflow is updated and saved successfully.")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()='${testName}']//following::button[2]`)
        methods.clickElementByXPath(locators.Remove_workflow)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.GetText(locators.notification_popup, "SuccessDeleted Workflow successfully")
        cy.wait(Timeout.xs)

    })

    it.skip('Apollo - Zoho', () => {

        const nowTime = dayjs().format('H:m:s');
        const testName = `Demo Apollo Zoho ${nowTime}`;
        const IntegrateName = "Integrate Zoho CRM";

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        cy.visit(`${envDetails.backendApiUrl}/automations/workflows`)
        cy.wait(Timeout.sm)
        methods.assertElementContainsTextxpath(locators.workflows_Title, 'Workflows')
        methods.VisibilityofElement(locators.identi_table)
        cy.wait(Timeout.xs)
        methods.ElementToBeClickableXpath(locators.workflow)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.workflow)
        methods.clickElementByXPath(locators.Zoho_template_Option)
        methods.clickElementByXPath(locators.Apollo_Zoho_Templete)
        methods.clickElementByXPath(locators.Use_this_template)
        methods.clickElement(locators.workflow_edit_icon)
        methods.ClearAndTypeWithXpath(locators.workflow_name, testName)
        methods.EnterXpath(locators.workflow_name)
        methods.clickElementByXPath(locators.select_event)
        methods.clickElement0(locators.others1, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Configure_Action)
        cy.wait(Timeout.lg)
        methods.assertElementContainsTextxpath(`(//span[text()="${IntegrateName}"]//following::h4)[1]`, "Connected")
        cy.wait(Timeout.xs)

        cy.xpath(`//div[@role="tablist"]//following::div[@role="tab"]`, { Timeout: extraTimeOut })
            .invoke('attr', 'aria-expanded')
            .then((Configure_expand) => {

                if (Configure_expand === "false") {
                    cy.log('**Dropdown is not expanded**');
                    methods.clickElementByXPath(locators.Configurations)
                } else {
                    cy.log('**Dropdown is already expanded, skipping click action**');
                }

            })

        methods.clickElementByXPath(locators.AddProperty)
        methods.clickElementIndexXpath(locators.Apollo_Select_Property, 0)
        methods.typeElementByXPathwithIndex(locators.Apollo_Select_Property, "Account Act", 0)
        methods.clickElement0(locators.AccountActivityURL, 0)
        methods.clickElementIndexXpath(locators.Apollo_Select_Property, 1)
        methods.typeElementByXPathwithIndex(locators.Apollo_Select_Property, "City", 1)
        methods.clickElement0(locators.BillingCity1, 0)
        methods.clickElementByXPath(locators.AddProperty)
        methods.clickElementIndexXpath(locators.Apollo_Select_Property, 2)
        methods.typeElementByXPathwithIndex(locators.Apollo_Select_Property, "In hu", 2)
        methods.clickElement0(locators.In_Hubspot2, 0)
        methods.clickElementIndexXpath(locators.Apollo_Select_Property, 3)
        methods.typeElementByXPathwithIndex(locators.Apollo_Select_Property, "Name", 3)
        methods.clickElement0(locators.AccountName, 0)
        methods.typeElement(locators.API_Input, APIKEY)
        methods.scrollWithXpath(locators.SaveandPublish)
        methods.typeElement(locators.person_titles, "Testing")
        methods.typeElement(locators.person_seniorities, "Testing")
        methods.typeElement(locators.Apollo_Person_locations, "India")
        methods.typeElement(locators.max_contacts, "10")
        methods.clickElementIndexXpath(locators.ContactProperties, 1)
        methods.clickElement0(locators.AccountName, 2)
        methods.clickElementIndexXpath(locators.ContactProperties, 3)
        methods.clickElement0(locators.Assistant, 1)
        methods.clickElementIndexXpath(locators.ContactProperties, 5)
        methods.clickElement0(locators.AsstPhone, 2)
        methods.clickElementIndexXpath(locators.ContactProperties, 7)
        methods.clickElement0(locators.ContactImage, 3)
        methods.clickElementIndexXpath(locators.ContactProperties, 9)
        methods.clickElement0(locators.ContactOwner, 4)
        methods.clickElementIndexXpath(locators.ContactProperties, 11)
        methods.clickElement0(locators.CreatedBy, 5)
        methods.clickElementIndexXpath(locators.ContactProperties, 13)
        methods.clickElement0(locators.DateofBirth, 6)
        methods.clickElementIndexXpath(locators.ContactProperties, 15)
        methods.clickElement0(locators.Department, 7)
        methods.clickElementByXPath(locators.SaveandPublish)
        methods.GetText(locators.notification_popup, "Workflow SavedNew workflow is created and saved successfully.")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()='${testName}']`)
        methods.clickElementByXPath(locators.Add_a_Filter)
        methods.clickElement0(locators.Hubspot_Contacts, 0)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.pageview_option1)
        cy.wait(Timeout.sm)
        methods.clickElement(locators.equals_1)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.Apply1)
        cy.wait(Timeout.xs)
        methods.ScrollAndClickxpath(locators.Delete_Company)
        cy.wait(Timeout.xs)
        methods.ScrollAndClickxpath(locators.SaveandPublish)
        methods.GetText(locators.notification_popup, "Workflow UpdatedWorkflow is updated and saved successfully.")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(`//h4[text()='${testName}']//following::button[2]`)
        methods.clickElementByXPath(locators.Remove_workflow)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.GetText(locators.notification_popup, "SuccessDeleted Workflow successfully")
        cy.wait(Timeout.xs)

    })
})